### ISSUE TITLE
Translations are not inheriting from ancestor models

### ISSUE THREAD

**Issue by daniel-rikowski** [activerecord-hackery/ransack#289]
Hello,

I have this model class structure:

``` ruby
module Products
  class Base < ActiveRecord::Base
  end
  class Product < Base
  end
end
```

And this translation file:

``` yaml
de:
  activerecord:
    attributes:
      products/base:
        price: Preis
```

Calling `Products::Product.human_attribute_name(:price)` return "Preis". 

But performing

``` ruby
@search = Products::Product.search(params[:q])
Ransack::Translate.attribute(:price, context: @search.context)
```

returns "Price" (the humanized attribute name fallback)

Note that this might be related with #273, but it is not the same. The suggested fix doesn't help with this problem.

But at least this fix allows me to duplicate the translation 

``` yaml
de:
  activerecord:
    attributes:
      products/base:
        price: Preis
      products/product:
        price: Preis
```

which then works correctly:

``` ruby
Products::Product.human_attribute_name(:price)                 # => "Preis"
Ransack::Translate.attribute(:price, context: @search.context) # => "Preis"
```

Currently I'm using

``` ruby
sort_link @search, :price, Products::Product.human_attribute_name(:price)
```

in my views. That works, but it would be nice if it weren't necessary. 

Thanks!

PS: I'm using Rails 4.0 and I tried the last released gem and the master branches from both ernie/ransack and jonatack/ransack.
