### ISSUE TITLE
Rails 4.2.0 API changes for Ransack form helpers placeholder text

### ISSUE THREAD

**Issue by jonatack** [activerecord-hackery/ransack#418]
If you are using Ransack with Rails 4.2.0.alpha after August 14, 2014, [Rails commit dfc3f88](https://github.com/rails/rails/commit/dfc3f88) changed how `placeholder` options in `search_field` / `text_field` helpers in Ransack search forms are handled by Rails.

The following no longer works with Rails 4.2.0:

``` erb
<%= search_form_for @q do |f| %>
  <%= f.search_field :name_cont, placeholder: t(:name) %>
  <%= f.search_field :articles_title_start, placeholder: t('.title') %>
  <%= f.submit %>
<% end %>
```

Instead of the placeholders being displayed correctly, the supplied values are ignored and a `humanized` version of the search method is displayed instead (i.e. "Name cont" and "Articles title start").

The solution I've found so far is to pass `placeholder: true` instead and update the I18n files with translations by search method, scoped by `'helpers.placeholder.q'`, as shown:

``` erb
<%= search_form_for @q do |f| %>
  <%= f.search_field :name_cont, placeholder: true %>
  <%= f.search_field :articles_title_start, placeholder: true %>
  <%= f.submit %>
<% end %>
```

```
  # en.yml
  helpers:
    select:
      prompt: "Select"
    submit:
      create: 'Create %{model}'
      update: 'Update %{model}'
      submit: 'Save %{model}'
      search: "Search"
    placeholder:
      q:
        name_cont: "Name contains..."
        articles_title_start: "Article title starts with..."
```
