### ISSUE TITLE
PR proposal

### ISSUE THREAD

**Issue by timoschilling** [activerecord-hackery/ransack#478]
ActiveAdmin will remove his translations for the predicates, to use the ransack translations in the future.
We have [~37 locales](https://github.com/activeadmin/activeadmin/tree/master/config/locales) at the moment, but they are limited to this keys:
```yaml
# at the moment they have the old metasearch key
      predicates:
        contains: "Enthält"
        equals: "Gleich"
        starts_with: "Beginnt mit"
        ends_with: "Endet mit"
        greater_than: "Größer als"
        less_than: "Kleiner als"

# but I will transform them to the ransack keys
      predicates:
        cont: "Enthält"
        eq: "Gleich"
        start: "Beginnt mit"
        end: "Endet mit"
        gt: "Größer als"
        lt: "Kleiner als"
```

I will create a PR with this keys for all locales that ransack don't have at the moment, if ransack will accept incomplete locales.
